name: Keep Supabase Awake

on:
  schedule:
    - cron: '*/15 * * * *' # every 15 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Insert a new row into stay-awake
        run: |
          curl -X POST 'https://wlhdifrealkmsiafaxzx.supabase.co/rest/v1/stay-awake' \
            -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsaGRpZnJlYWxrbXNpYWZheHp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDU4NjIsImV4cCI6MjA2NTUyMTg2Mn0.XCkuw2NW1-zREzbg9fvq5a2RiYFym6lnI28LZkUbuiA" \
            -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsaGRpZnJlYWxrbXNpYWZheHp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDU4NjIsImV4cCI6MjA2NTUyMTg2Mn0.XCkuw2NW1-zREzbg9fvq5a2RiYFym6lnI28LZkUbuiA" \
            -H "Content-Type: application/json" \
            -d '{}'

      - name: Delete the oldest row from stay-awake
        run: |
          curl -X DELETE 'https://wlhdifrealkmsiafaxzx.supabase.co/rest/v1/stay-awake?order=created_at.asc&limit=1' \
            -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsaGRpZnJlYWxrbXNpYWZheHp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDU4NjIsImV4cCI6MjA2NTUyMTg2Mn0.XCkuw2NW1-zREzbg9fvq5a2RiYFym6lnI28LZkUbuiA" \
            -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsaGRpZnJlYWxrbXNpYWZheHp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDU4NjIsImV4cCI6MjA2NTUyMTg2Mn0.XCkuw2NW1-zREzbg9fvq5a2RiYFym6lnI28LZkUbuiA" \
            -H "Content-Type: application/json" \
            -H "Prefer: resolution=merge-duplicates"
